services:
  - type: web
    name: baby-cry-sense-tool # आपके प्रोजेक्ट का नाम
    env: python
    buildCommand: "pip install -r requirements.txt"
     startCommand: "gunicorn --bind 0.0.0.0:10000 --timeout 300 --workers 1 app:app" 
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13 # === इसे 3.10.13 (या 3.9.18 या 3.11.8) पर बदलें ===
    autoDeploy: true
    pullRequestPreviewsEnabled: false
    rootDir: "" # इसे खाली रहने दें, क्योंकि आपकी फाइलें रेपो रूट में हैं
